django_foodmenu/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import food.views
from django_foodmenu import settings
from users import views as user_views
from django.contrib.auth import views as auth_views


"""
This class is used to configure the URLS.
We add static, because the static files are in a separate folder and configured here in the admin app.
"""
urlpatterns = [
    path('', food.views.IndexClassListView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views

"""
The following code is used to create the URL patterns for the food app. So, any URL for the below list should start with /food/. 
pk is the primary key of the food item. The primary key is the unique identifier for the food
"""
app_name = 'food'
urlpatterns = [
    path('', views.IndexClassListView.as_view(), name='index'),
    path('<int:pk>/', views.FoodItemDetailView.as_view(), name='detail'),
    path('add/', views.FoodItemCreateView.as_view(), name='create_item'),
    path('update/<int:pk>/', views.FoodItemUpdateView.as_view(), name='update_item'),
    path('delete/<int:pk>/', views.FoodItemDeleteView.as_view(), name='delete_item'),
]

food/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class FoodItem(models.Model):
    """
    This class is used to create a model for the food items.
    A model is a representation of the data that will be stored in the database.
    """
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=255)
    item_desc = models.CharField(max_length=255)
    item_price = models.DecimalField(max_digits=5, decimal_places=2)
    item_image = models.CharField(max_length=1024, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def __str__(self):
        """
        This method is used to return the name of the food item, instead of a model object.
        """
        return self.item_name

    def get_absolute_url(self):
        """
        This method is used to return the URL to access a detailed record for this food item.
        """
        return reverse('food:detail', kwargs={'pk': self.pk})

users/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):
    """
    This class is used to configure the profile model.

    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=100, blank=True, default='')

    def __str__(self):
        return f'{self.user.username}'

food/forms.py
from django import forms
from .models import FoodItem

class FoodItemForm(forms.ModelForm):
    """
    This class is used to create a form for the FoodItem model. The fields are the attributes of the FoodItem model.
    """
    class Meta:
        """
        This class is used to define the model and the fields of the model that will be used in the form.
        Django will automatically create the form fields for the model fields.
        """
        model = FoodItem
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

    def __init__(self, *args, **kwargs):
        """
        This method is used to add attributes to the form fields. In this case, the class attribute is added to the form fields.
        They are added to the form fields so that the Bootstrap classes can be used to style the form fields.
        """
        super().__init__(*args, **kwargs)
        self.fields['item_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['item_desc'].widget.attrs.update({'class': 'form-control'})
        self.fields['item_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['item_image'].widget.attrs.update({'class': 'form-control'})

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    """
    This class is used to configure the registration form by adding the email field to the pre-configured registration form of django.
    """
    email = forms.EmailField()

    class Meta:
        """
        This class is used to configure the model and fields of the registration form.
        To represent what fields are shown in the registration form.
        """
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import generic
from .models import FoodItem



class IndexClassListView(generic.ListView):
    """
    Generic class-based view for displaying a list of items.
    """
    model = FoodItem
    template_name = 'food/index.html'
    context_object_name = 'item_list'


class FoodItemDetailView(generic.DetailView):
    """
    Class-based detailed view for a food item.
    """
    model = FoodItem
    template_name = 'food/detail.html'
    # context_object_name = 'item'


class FoodItemCreateView(generic.CreateView):
    """
    Class-based view for creating a food item.
    The dispatch method is used to ensure that only logged in users can create a food item.
    """
    model = FoodItem
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item_form.html'

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


class FoodItemUpdateView(generic.UpdateView):
    """
    Class-based view for updating a food item.
    """
    model = FoodItem
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item_form.html'

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


class FoodItemDeleteView(generic.DeleteView):
    """
    Class-based view for deleting a food item.
    """
    model = FoodItem
    success_url = '/food/'
    template_name = 'food/item_delete.html'

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# Views that are no longer used, but are kept for reference. Function based views

# def delete_item(request, id):
#     item = FoodItem.objects.get(pk=id)
#     if request.method == 'POST':
#         item.delete()
#         return redirect('food:index')
#     return render(request, 'food/item_delete.html', {'item': item})

# def update_item(request, id):
#     item = FoodItem.objects.get(pk=id)
#     form = FoodItemForm(request.POST or None, instance=item)
#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
#     return render(request, 'food/item_form.html', {'form': form, 'item': item})

# def detail(request, item_id):
#     item = FoodItem.objects.get(pk=item_id)
#     context = {
#         'item': item,
#     }
#     return render(request, 'food/detail.html', context)

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from users.forms import RegisterForm
from users.models import Profile


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Profile.objects.create(user=user)
            # create a new profile for the user
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Food App</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'food:index' %}">Food App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'food:create_item' %}">Add Item</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li>
                        <a class="nav-link active" href="{% url 'profile' %}">Profile</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% block body %}
{% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
        <div>
            <img src="{{ object.item_image }}" height="400" width="400" alt="{{ object.item_name }}" class="img-fluid mb-3">
            <h3>{{ object.item_name }}</h3>
            <h3>{{ object.item_desc }}</h3>
            <h3>${{ object.item_price }}</h3>
            <h3>Added by {{ object.user_name  }}</h3>
            <a href="{% url 'food:delete_item' object.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'food:update_item' object.id %}" class="btn btn-primary">Update</a>
        </div>
    </div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            {% for item in item_list %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img class="card-img-top" src="{{ item.item_image }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ item.item_name }}</h5>
                            <p class="card-text">${{ item.item_price }}</p>
                            <a href="{% url 'food:detail' item.id %}" class="btn btn-primary float-end">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

food/templates/food/item_delete.html
{#{% extends 'food/base.html' %}#}
{#{% block body %}#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        <div class="container mt-3">#}
{#            <div class="alert alert-success alert-dismissible fade show" role="alert">#}
{#                <h4 class="alert-heading">Are you sure you want to delete?</h4>#}
{#                <p class="mb-0">You can continue to manage your items or return to the main page.</p>#}
{#                <button type="submit" class="btn-close" data-bs-dismiss="alert" aria-label="Close">Submit</button>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}
{#{% endblock %}#}

{% extends 'food/base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        <div class="container mt-3">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <h4 class="alert-heading">Are you sure you want to delete?</h4>
                <p>You can continue to manage your items or return to the main page.</p>
                <hr>
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

food/templates/food/item_form.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto mt-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Your Form Title</h3>
                    </div>
                    <div class="card-body">
                        <form method="post" novalidate>
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group mb-3">
                                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                                    <input type="{{ field.field.widget.input_type }}" class="form-control{% if field.errors %} is-invalid{% endif %}" id="{{ field.id_for_label }}" name="{{ field.html_name }}" placeholder="Enter your {{ field.label }}" value="{{ field.value|default:'' }}" {% if field.field.required %}required{% endif %}>
                                    {% for error in field.errors %}
                                        <div class="invalid-feedback d-block">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                            <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto mt-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Login</h3>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <label for="{{ form.username.id_for_label }}">Username:</label>
                                <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}" placeholder="Enter your username" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="{{ form.password.id_for_label }}">Password:</label>
                                <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" placeholder="Enter your password" required>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/logout.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="alert alert-success text-center" role="alert" style="width: 50%;">
            You have been logged out
            <div class="mt-3">
                <a href="{% url 'food:index' %}" class="btn btn-danger">Go Back</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <img class="user one" src="{{ user.profile.image.url }}" alt="{{ user.username }}'s profile picture">
        <h1>{{ user.username }}</h1>
    </div>
{% endblock %}

users/templates/users/register.html
{#{% extends 'food/base.html' %}#}
{#{% block body %}#}
{#    <div class="container">#}
{#        <div class="row">#}
{#            <div class="col-md-6 mx-auto mt-5">#}
{#                <div class="card">#}
{#                    <div class="card-header">#}
{#                        <h3 class="text-center">Sign Up</h3>#}
{#                    </div>#}
{#                    <div class="card-body">#}
{#                        <form method="post">#}
{#                            {% csrf_token %}#}
{#                            {% for field in form %}#}
{#                                <div class="form-group mb-3">#}
{#                                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>#}
{#                                    <input type="{{ field.field.widget.input_type }}" class="form-control{% if field.errors %} is-invalid{% endif %}" id="{{ field.id_for_label }}" name="{{ field.html_name }}" placeholder="Enter your {{ field.label }}" {% if field.field.required %}required{% endif %}>#}
{#                                    {% for error in field.errors %}#}
{#                                        <div class="invalid-feedback d-block">#}
{#                                            {{ error }}#}
{#                                        </div>#}
{#                                    {% endfor %}#}
{#                                </div>#}
{#                            {% endfor %}#}
{#                            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}



{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto mt-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Sign Up</h3>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group mb-3">
                                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                                    <input type="{{ field.field.widget.input_type }}" class="form-control{% if field.errors %} is-invalid{% endif %}" id="{{ field.id_for_label }}" name="{{ field.html_name }}" placeholder="Enter your {{ field.label }}" value="{{ field.value|default:'' }}" {% if field.field.required %}required{% endif %}>
                                    {% for error in field.errors %}
                                        <div class="invalid-feedback d-block">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}